### PR TITLE
:bug: Enable dependency rules analysis in source-only mode

### LINKED ISSUE #184: :bug: Can not run dependency rules with source only mode
https://github.com/konveyor/tackle2-addon-analyzer/blob/main/cmd/mode.go#L51-L59

Today, it appears that when the source-only mode is set, dependency rules are disabled. This means that rules that would use the ``<provider> .dependency``` capability will not run. 

I don't believe this is a valid restriction and should be changed to align with other projects in the organization.

### PR DESCRIPTION
**Pull request by mguetta1**
Fixes #184 
Fixes https://github.com/konveyor/analyzer-lsp/issues/936

API tests PR: 379

## Summary by CodeRabbit

* **Refactor**
  * Simplified analysis configuration handling to improve consistency with default behavior.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: cmd/mode.go [hunk 1]
```diff
@@ -53,7 +53,6 @@ func (r *Mode) AddOptions(options *command.Options, settings *Settings) (err err
 		settings.Mode(provider.FullAnalysisMode)
 	} else {
 		settings.Mode(provider.SourceOnlyAnalysisMode)
-		options.Add("--no-dependency-rules")
```
Comment (shawn-hurley) [inline cmd/mode.go]: Shouldn't there be some way to turn off the dependency rules?
